{"uid":"a0d1cc525db49a70","name":"test_username_already_in_use","fullName":"tests.api.test_api_signup#test_username_already_in_use","historyId":"614b0c58f31a968107c516c2dff127f4","time":{"start":1718131876756,"stop":1718131877060,"duration":304},"status":"failed","statusMessage":"AssertionError: Expected status code 422\nassert 201 == 422\n +  where 201 = <Response [201]>.status_code","statusTrace":"sign_up_api = <api.post_sign_up.SignUp object at 0x7f30690d6690>\n\n    def test_username_already_in_use(sign_up_api: SignUp):\n        user = get_random_user()\n        user.username = \"existing_user\"\n        response = make_request_and_log(sign_up_api, user)\n>       assert response.status_code == 422, \"Expected status code 422\"\nE       AssertionError: Expected status code 422\nE       assert 201 == 422\nE        +  where 201 = <Response [201]>.status_code\n\ntests/api/test_api_signup.py:47: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_session_faker","time":{"start":1718131874822,"stop":1718131874839,"duration":17},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false},{"name":"sign_up_api","time":{"start":1718131876755,"stop":1718131876755,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: Expected status code 422\nassert 201 == 422\n +  where 201 = <Response [201]>.status_code","statusTrace":"sign_up_api = <api.post_sign_up.SignUp object at 0x7f30690d6690>\n\n    def test_username_already_in_use(sign_up_api: SignUp):\n        user = get_random_user()\n        user.username = \"existing_user\"\n        response = make_request_and_log(sign_up_api, user)\n>       assert response.status_code == 422, \"Expected status code 422\"\nE       AssertionError: Expected status code 422\nE       assert 201 == 422\nE        +  where 201 = <Response [201]>.status_code\n\ntests/api/test_api_signup.py:47: AssertionError","steps":[],"attachments":[{"uid":"128fed96293edb7b","name":"log","source":"128fed96293edb7b.txt","type":"text/plain","size":1564}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true},"afterStages":[],"labels":[{"name":"parentSuite","value":"tests.api"},{"name":"suite","value":"test_api_signup"},{"name":"host","value":"fv-az1773-913"},{"name":"thread","value":"3482-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.api.test_api_signup"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"a0d1cc525db49a70.json","parameterValues":[]}